process.env.APP_NAME = "psc-extensions-web";
process.env.LOG_LEVEL = "info";
process.env.NODE_ENV = "dev";
process.env.NODE_PORT = "3000";
process.env.NUNJUCKS_LOADER_WATCH = "false";
process.env.NUNJUCKS_LOADER_NO_CACHE = "true";
process.env.CHS_URL = "http://chsurl.co";
process.env.API_URL = "http://testapi.co";
process.env.COOKIE_SECRET = "Xy6onkjQWF0TkRn0hfdqUw==";
process.env.COOKIE_DOMAIN = "cookie domain";
process.env.CACHE_SERVER = "test";
process.env.COOKIE_NAME = "cookie_name";
process.env.LOCALES_ENABLED = "true";
process.env.CHS_API_KEY = "CHS_API_KEY";
process.env.CHS_INTERNAL_API_KEY = "CHS_INTERNAL_API_KEY";
